--------STORED PROCE

USE ETRADE
ALTER PROC SP_SATISLAR
@BASTARIH DATE,
@BITTARIH DATE,
@SEHIR VARCHAR(20) = '%'
AS
BEGIN
SELECT U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, U.TELNR1, U.TELNR2,
	C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE,
	A.ADDRESSTEXT ACIKADRES, O.ID SIPARISID, ITM.ITEMCODE URUNKODU, ITM.ITEMNAME URUNADI, ITM.BRAND MARKA,
	OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT, OD.LINETOTAL SATIRTOPLAMI
FROM ORDERDETAILS OD
	INNER JOIN ORDERS O ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
WHERE O.DATE_ BETWEEN @BASTARIH AND @BITTARIH AND CT.CITY LIKE @SEHIR
END

EXEC SP_SATISLAR '20190101','20190131','aDANA'

USE HR
ALTER PROCEDURE [dbo].[WORKER_INOUT]
@WORKERBARCODE AS VARCHAR(100),
@IOTYPE AS VARCHAR(1),
@DATE DATETIME
AS
BEGIN
	DECLARE @WORKERID AS INT
	DECLARE @WORKERNAME AS VARCHAR(100)
	SELECT @WORKERID=ID,@WORKERNAME=WORKERNAME FROM WORKERS WHERE BARCODE=@WORKERBARCODE 

	IF @WORKERID IS NULL
	BEGIN
		RAISERROR('Bu kart kayýtlý deðildir',16,1)
		RETURN
	END

	DECLARE @LASTIOTYPE AS VARCHAR(1)
	SELECT TOP 1 @LASTIOTYPE=IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID=@WORKERID
	AND DATE_>=CONVERT(DATE,GETDATE()) 
	ORDER BY DATE_ DESC,ID DESC 

	IF @LASTIOTYPE=@IOTYPE
	BEGIN
		IF @IOTYPE='G'
		BEGIN
			RAISERROR('Zaten içeride görünüyorsunuz.',16,1)
			RETURN
		END
		IF @IOTYPE='C'
		BEGIN
			RAISERROR('Zaten dýþarýda görünüyorsunuz.',16,1)
			RETURN
		END
	
	INSERT INTO WORKERTRANSACTIONS
	(WORKERID,IOTYPE,DATE_)
	VALUES
	(@WORKERID,@IOTYPE,@DATE)

	SELECT @WORKERNAME AS WORKERNAME,@DATE AS DATE_
END


--Store procedure üzerinden azaltma vb isteniyorsa store procedure sonucu geçiçi tabloya atanarak iþlem yapýlabilir.
--INSERT INTO __GEÇÝCÝTABLOISMI__ EXEC ____PROCEDURE YAZIMI____ ile sonuç çýktýsý elde edilebilir